service: sls-training

provider:
    name: aws
    runtime: nodejs12.x
    stage: dev
    region: us-east-1

environment:
    A_GLOBAL_VAR: 'Esta es una variable de entorno global'

functions:
    LookAtThisLambda:
        handler: handler.lookAtThisLambda
        events:
        - http:
            path: users/create
            method: get
        environment:
            A_LAMBDA_VAR: 'Esta es una variable para esta lambda'

resources:
  Resources:
    NewResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: my-new-bucket
