service: sls-training

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

functions:
  LookAtThisLambda:
    handler: src/lookAtThisLambda.handler
    environment:
      AN_ENV_VAR: 'Una variable util'
    events:
      - http:
          path: training-sls/first
          method: post
          cors: true
